repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1024']
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.21.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: ['--config', 'pyproject.toml']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        additional_dependencies:
          [
            'flake8-broken-line==0.3.0',
            'flake8-bugbear==21.4.3',
            'flake8-builtins==1.5.3',
            'flake8-comprehensions==3.5.0',
            'flake8-polyfill==1.0.2',
            'flake8-return==1.1.3',
            'flake8-simplify==0.14.1',
          ]
